name: ml
channels:
  - pytorch
  - defaults
dependencies:
  - _libgcc_mutex=0.1=main
  - blas=1.0=mkl
  - ca-certificates=2019.11.27=0
  - certifi=2019.11.28=py37_0
  - cffi=1.13.2=py37h2e261b9_0
  - cudatoolkit=10.1.243=h6bb024c_0
  - freetype=2.9.1=h8a8886c_1
  - intel-openmp=2019.4=243
  - joblib=0.14.1=py_0
  - jpeg=9b=h024ee3a_2
  - ld_impl_linux-64=2.33.1=h53a641e_7
  - libedit=3.1.20181209=hc058e9b_0
  - libffi=3.2.1=hd88cf55_4
  - libgcc-ng=9.1.0=hdf63c60_0
  - libgfortran-ng=7.3.0=hdf63c60_0
  - libpng=1.6.37=hbc83047_0
  - libstdcxx-ng=9.1.0=hdf63c60_0
  - libtiff=4.1.0=h2733197_0
  - mkl=2019.4=243
  - mkl-service=2.3.0=py37he904b0f_0
  - mkl_fft=1.0.15=py37ha843d7b_0
  - mkl_random=1.1.0=py37hd6b4f25_0
  - ncurses=6.1=he6710b0_1
  - ninja=1.9.0=py37hfd86e86_0
  - numpy=1.17.4=py37hc1035e2_0
  - numpy-base=1.17.4=py37hde5b4d6_0
  - olefile=0.46=py37_0
  - openssl=1.1.1d=h7b6447c_3
  - pandas=0.25.3=py37he6710b0_0
  - pillow=7.0.0=py37hb39fc2d_0
  - pip=19.3.1=py37_0
  - pycparser=2.19=py37_0
  - python=3.7.6=h0371630_1
  - python-dateutil=2.8.1=py_0
  - pytorch=1.3.1=py3.7_cuda10.1.243_cudnn7.6.3_0
  - pytz=2019.3=py_0
  - readline=7.0=h7b6447c_5
  - setuptools=44.0.0=py37_0
  - six=1.13.0=py37_0
  - sqlite=3.30.1=h7b6447c_0
  - tk=8.6.8=hbc83047_0
  - torchvision=0.4.2=py37_cu101
  - wheel=0.33.6=py37_0
  - xz=5.2.4=h14c3975_4
  - zlib=1.2.11=h7b6447c_3
  - zstd=1.3.7=h0b5b093_0
  - pip:
    - attrs==19.3.0
    - backcall==0.1.0
    - bleach==3.1.0
    - catboost==0.20.2
    - chardet==3.0.4
    - cycler==0.10.0
    - decorator==4.4.1
    - defusedxml==0.6.0
    - entrypoints==0.3
    - idna==2.8
    - importlib-metadata==1.3.0
    - ipykernel==5.1.3
    - ipython==7.11.1
    - ipython-genutils==0.2.0
    - ipywidgets==7.5.1
    - jedi==0.15.2
    - jinja2==2.10.3
    - json5==0.8.5
    - jsonschema==3.2.0
    - jupyter==1.0.0
    - jupyter-client==5.3.4
    - jupyter-console==6.0.0
    - jupyter-core==4.6.1
    - jupyterlab==1.2.4
    - jupyterlab-server==1.0.6
    - kaggle==1.5.6
    - kiwisolver==1.1.0
    - lightgbm==2.3.1
    - markupsafe==1.1.1
    - matplotlib==3.1.2
    - mistune==0.8.4
    - more-itertools==8.0.2
    - nbconvert==5.6.1
    - nbformat==5.0.3
    - notebook==6.0.2
    - pandocfilters==1.4.2
    - parso==0.5.2
    - pexpect==4.7.0
    - pickleshare==0.7.5
    - plotly==4.4.1
    - prometheus-client==0.7.1
    - prompt-toolkit==2.0.10
    - ptyprocess==0.6.0
    - pygments==2.5.2
    - pyparsing==2.4.6
    - pyrsistent==0.15.7
    - python-graphviz==0.13.2
    - python-slugify==4.0.0
    - pyzmq==18.1.1
    - qtconsole==4.6.0
    - requests==2.22.0
    - retrying==1.3.3
    - scikit-learn==0.22.1
    - scipy==1.4.1
    - send2trash==1.5.0
    - terminado==0.8.3
    - testpath==0.4.4
    - text-unidecode==1.3
    - tornado==6.0.3
    - tqdm==4.41.1
    - traitlets==4.3.3
    - urllib3==1.24.3
    - wcwidth==0.1.8
    - webencodings==0.5.1
    - widgetsnbextension==3.5.1
    - xgboost==0.90
    - zipp==0.6.0

